### ISSUE TITLE
Always prepend a colon when sending privmsg

### ISSUE THREAD

**Issue by xPaw** [kiwiirc/irc-framework#53] opened 2016-06-05 21:10 UTC
One of @thelounge users ran into issue where messages without spaces (no colon prepended) are being ignored by the server.

**Comment by dgw** [comment] 2016-06-13 03:50
Probably fixed by #45, whenever that gets merged in.

**Comment by xPaw** [comment] 2016-06-13 07:01
@dgw It won't. There won't be any colons added to a `hello` message.

**Comment by prawnsalad** [comment] 2017-07-20 19:07
Closing due to fix applied some releases ago

**Comment by xPaw** [comment] 2017-07-20 19:08
@prawnsalad was it though?

**Closed by prawnsalad** 2017-07-20 19:07 UTC

**Comment by prawnsalad** [comment] 2017-07-20 19:15
Ah sorry, re-read this specific issue. So the issue is the server doesn't parse IRC messages correctly. Which IRCd was it?

**Comment by xPaw** [comment] 2017-07-20 19:16
I believe it was some custom proxy.

**Comment by prawnsalad** [comment] 2017-07-20 19:17
Then they should fix the proxy.
